apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgarett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rgarett
  template:
    metadata:
      labels:
        app: rgarett
    spec:
      containers:
      - image: okteto.dev/rgarett:latest
        name: rgarett
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bdab9c45-f5a3-4a96-bf42-bbed4ea065c9"
        - name: Vless_Path
          value: "/vl5ryiy55"
        - name: Vmess_UUID
          value: "bdab9c45-f5a3-4a96-bf42-bbed4ea065c9"
        - name: Vmess_Path
          value: "/vm6hdc4h66"
        - name: Share_Path
          value: "/v2link"
